---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
#| include: false
library(tidyverse)
source(here::here("R/functions.R"))
lipidomics <- read_csv(here::here("data/lipidomics.csv"))
```

## Basic statistics

```{r}
lipidomics |>
  group_by(metabolite) |>
  summarise(
    across(
      value,
      list(
        mean = mean, # This is the function name
        sd = sd
      )
    )
  ) |>
  mutate(across(where(is.numeric), ~ round(.x, digits = 1)))


#' Title: Descriptive Statistics Table
#'
#' @param data 
#'
#' @return A data.frame/tibble

descriptive_stats <- function(data) {
  data |>
    dplyr::group_by(metabolite) |>
    dplyr::summarise(
      dplyr::across(
        value,
        list(
          mean = mean, # This is the function name
          sd = sd
        )
      )
    ) |>
    dplyr::mutate(
      dplyr::across(
        dplyr::where(is.numeric), ~ round(.x, digits = 1)
      )
    )
}



# Replace the target list below with your own:
list(
    tar_target(
        name = file, 
        command = "data/lipidomic.csv", 
        format = "file"),
  tar_target(
      name = lipidomics,
      command = readr::read_csv(here::here("data/lipidomics.csv"))
  ),
  tar_target(
      name = df_stats_by_metabolite,
      command = descriptive_stats(lipidomics)
  )
)



tar_read(df_stats_by_metabolite) |> 
    mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |> # R object in {...}, everything outside {} is text
    select(Metabolite = metabolite, `Mean (SD)` = MeanSD)

use_git_ignore("doc/notes.qmd") # To not upload to github

```
